packages:
  - .
  - ./client
  - ./platform
  - ./platform/function

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - unrs-resolver

overrides:
  '@eslint/js': ^9
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<8.18.0: '>=8.18.0'
  eslint: ^9
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
