packages:
  - .
  - ./client
  - ./platform
  - ./platform/function

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - unrs-resolver

overrides:
  axios@=1.10.0: '>=1.11.0'
