packages:
  - .
  - ./client
  - ./platform
  - ./platform/function

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - unrs-resolver

overrides:
  ai@<5.0.52: '>=5.0.52'
  axios@=1.10.0: '>=1.11.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  hono@>=4.8.0 <4.9.6: '>=4.9.6'
  jsondiffpatch@<0.7.2: '>=0.7.2'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
